INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Status de criação do evento no diario de bordo', 'EVENTO_CRIADO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Status de reabertura de evento no diario de bordo', 'EVENTO_REABERTO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Status quando o evento já existe no diario de bordo', 'EVENTO_JA_EXISTE');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Status quando o evento já se encontra aberto no diario de bordo', 'EVENTO_ESTA_ABERTO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Status quando o evento está em processo de classificação no diario de bordo', 'EVENTO_EM_CLASSIFICACAO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Status quando o evento já está fechado', 'EVENTO_JA_FECHADO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Status quando o evento não existe no diario de bordo', 'EVENTO_NAO_EXISTE');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Status quando o numero do incidente está invalido', 'INCIDENTE_INVALIDO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Evento associado com sucesso', 'EVENTO_ASSOCIADO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Número do incidente pai inválido', 'NUMERO_INCIDENTE_PAI_INVALIDO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Número do incidente filho inválido', 'NUMERO_INCIDENTE_FILHO_INVALIDO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Incidente pai não existe no Diario de Bordo', 'EVENTO_PAI_NAO_EXISTE');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Incidente filho não existe no Diario de Bordo', 'EVENTO_FILHO_NAO_EXISTE');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Associação já existente no Diario de Bordo', 'ASSOCIAÇÃO_JA_EXISTENTE');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Incidente pai informado é um incidente filho no Diario de Bordo', 'EVENTO_PAI_INFORMADO_E_UM_EVENTO_FILHO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Incidente filho informado é um incidente pai no Diario de Bordo', 'EVENTO_FILHO_INFORMADO_E_UM_EVENTO_PAI');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Evento desassociado com sucesso', 'EVENTO_DESASSOCIADO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'A associação não existe no Diario de Bordo', 'ASSOCIAÇÃO_NAO_EXISTE');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Comentário inserido com sucesso', 'COMENTARIO_INSERIDO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'O comentário não pode ser inserido no Diario de Bordo', 'COMENTARIO_INVALIDO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Não foi possivel inserir o comentário pois o evento já está fechado no Diario de Bordo', 'EVENTO_FECHADO');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Status quando a data informada está em formato incorreto', 'DATA_INVALIDA');
INSERT INTO tb_status_retorno_diario_bordo (data_criacao, descricao, nome) VALUES (now(), 'Status quando ocorreu um erro interno no diario de bordo', 'ERRO_INTERNO_DIARIO_BORDO');